steps:
  - label: ":php: check"
    agents:
      queue: "default"
      docker: "*"
    command: "echo Hello World"
    plugins:
      - docker-compose#v3.1.0:
          run: build
          config: docker/buildkite/docker-compose.yml

